---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:jvdiago/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: 10.0.2.15:5000/podinfo
      tag: stg-xfp4rrph
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
